### ISSUE TITLE
split doesn't work on windows

### ISSUE THREAD

**Issue by jamisonjangula** [jamisonjangula/canbus#2]
Traceback (most recent call last):
  File "F:\coursesUND\EE480\can_bus_software\can_stethoscope\src\can_stethoscope\main.py", line 17, in <module>
    main()
  File "F:\coursesUND\EE480\can_bus_software\can_stethoscope\src\can_stethoscope\main.py", line 10, in main
    file_manager.process_raw_filenames()
  File "F:\coursesUND\EE480\can_bus_software\can_stethoscope\src\can_stethoscope\file_manager.py", line 70, in process_raw_filenames
    split_file_list = self._find_split_files()
  File "F:\coursesUND\EE480\can_bus_software\can_stethoscope\src\can_stethoscope\file_manager.py", line 58, in _find_split_files
    return [each_file for each_file in self.raw_data_location.iterdir() if self._is_split_name(each_file.name)]
    return [each_file for each_file in self.raw_data_location.iterdir() if self._is_split_name(each_file.name)]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1160, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\coursesUND\\EE480\\can_bus_software\\can_stethoscope\\src\\can_stethoscope\\raw_can_data'

**Comment by makix222** [comment]
file ingestion can work on a single raw large file.
